# Markdownlint-cli2 options configuration for JaxMARL
# Documentation: https://github.com/DavidAnson/markdownlint-cli2
# NOTE: Lint rule settings are in .markdownlint.json

# Ignore specific files/patterns
ignores:
  - "**/node_modules/**"
  - "**/CHANGELOG.md"
  - ".local/**"
  - "site/**"
